version: '3.12'

services:
  app:
    build: .
    container_name: product
    ports:
      - '8000:8000'
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@db:5432/$${POSTGRES_DB}
    depends_on:
      - db
    command: sh -c 'alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: